#!/bin/bash
if echo "$0" | grep -E -v "bash-debug|systemd" > /dev/null; then  cd "${0%/*}"  ;fi  # cd this file folder
LocommitCommand="../bin/locommit"

function  AllTest() {
    DetectTestEnvironment

    Test_Error
    Test_ResolvePath
    Test_Assert
    Test_CutLastOf
    Test_CopyFolder
    Test_LessThanVersion
    Test_ErrorIfLastIs

    Test_1
    Test_Clone
    Test_ChangeAndClone
    Test_InWorkingDirectory
    Test_InWorkingSubDirectory
    Test_NoUpdate
    Test_NoModifiedConflict
    Test_NoGitOption
    Test_Diff
    Test_Diff_InWorkingDirectory
    Test_Diff_InWorkingSubDirectory
    Test_Push_1
    Test_Push_NoCommitNewNoDiff
    Test_Push_NoCommitError
    Test_Push_Null
    Test_Push_RemovedFiles
    Test_Push_SameOrParentFolderError
    Test_Pull_1
    Test_Pull_NoInput
    Test_Pull_Merge
    Test_Pull_Conflict
    Test_Pull_IgnoreInRepository
    Test_Pull_Push_InWorkingSubDirectory
    Test_Pull_Push_TargetInWorkingDirectory
    Test_PullBase_1
    Test_PullBase_NoInput
    Test_PullBase_Conflict
    EndOfTest
}

function  Test_1() {
    echo  ""
    echo  "### Test_1"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    echo "x" > "_testing/build/out"
    echo "x" > "_testing/example.txt"
    echo "build"      > "_testing/.gitignore"
    echo ".commit"   >> "_testing/.gitignore"
    echo ".commit_*" >> "_testing/.gitignore"
    echo ""
    echo "Test_1"

    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertExist     "_testing/.commit/example.txt"
    AssertExist     "_testing/.commit/.gitignore"
    AssertNotExist  "_testing/.commit/build"
    AssertNotExist  "_testing/.commit/build/out"
    if [ "${InGitWorking}" == "${False}" ]; then
        AssertExist     "_testing/.git"
    fi
    AssertReadOnly  "_testing/.commit/example.txt"
    AssertReadOnly  "_testing/.commit/.gitignore"
    DeleteFolder  "_testing"
}

function  Test_Clone() {
    echo  ""
    echo  "### Test_Clone"
    DeleteFolder  "_testing"
    mkdir -p  "_testing/repository/build"
    mkdir -p  "_testing/repository/sub"

    #// Set up
    echo "x" > "_testing/repository/a.txt"
    echo "x" > "_testing/repository/build/out"
    echo "x" > "_testing/repository/sub/b.txt"
    echo "build"      > "_testing/repository/.gitignore"
    echo ".commit"   >> "_testing/repository/.gitignore"
    echo ".commit_*" >> "_testing/repository/.gitignore"

    #// Main
    "${LocommitCommand}" clone "_testing/repository" "_testing/a/work"  ||  Error

    #// Check
    AssertNotReadOnly  "_testing/a/work/a.txt"
    AssertNotReadOnly  "_testing/a/work/sub/b.txt"
    AssertNotExist     "_testing/a/work/build/out"
    AssertReadOnly     "_testing/a/work/.commit/a.txt"
    AssertReadOnly     "_testing/a/work/.commit/sub/b.txt"
    AssertNotExist     "_testing/a/work/.commit/build/out"
    AssertExist        "_testing/a/work/.git"

    #// Set up
    echo  "Error test:"
    rm  "_testing/a/work/a.txt"  #// Because of checking not to copy it by clone

    #// Main
    "${LocommitCommand}" clone "_testing/repository" "_testing/a/work"  &&  Error

    #// Check
    AssertNotExist  "_testing/a/work/a.txt"
    DeleteFolder  "_testing"
}

function  Test_ChangeAndClone() {
    echo  ""
    echo  "### Test_ChangeAndClone"
    DeleteFolder  "_testing"
    mkdir -p  "_testing/repository"

    #// Set up
        #// Make a repository
        echo "x" > "_testing/repository/edit.txt"
        echo "x" > "_testing/repository/ignored.txt"
        echo ".commit"    > "_testing/repository/.gitignore"
        echo ".commit_*" >> "_testing/repository/.gitignore"
        pushd  "_testing/repository"  > /dev/null
        git init ${GitInitOption}  > /dev/null  2>&1
        git config --local user.email "${LocommitEMail}"
        git config --local user.name  "${LocommitUser}"
        git add "."  > /dev/null  2>&1
        git commit  -m "Already files exist"  > /dev/null  2>&1
        popd  > /dev/null

        #// Edit files in the repository folder
        echo "edited"       > "_testing/repository/edit.txt"
        echo "ignored.txt" >> "_testing/repository/.gitignore"
        echo "new"          > "_testing/repository/new.txt"

    #// Main
    "${LocommitCommand}" clone "_testing/repository" "_testing/a/work"  ||  Error

    #// Check
    if [ "$( cat    "_testing/a/work/edit.txt" )" != "edited" ]; then  Error  ;fi
    AssertNotExist  "_testing/a/work/ignored.txt"
    if [ "$( cat    "_testing/a/work/new.txt" )" != "new" ]; then  Error  ;fi
    rm -rf  "_testing/a/work"

    #// Set up
    echo  "Error test:"
    echo ".commit"    > "_testing/repository/.gitignore"
    echo ".commit_*" >> "_testing/repository/.gitignore"
    pushd  "_testing/repository"  > /dev/null
    git reset  > /dev/null
    echo "edited2"  > "edit.txt"
    git add           "edit.txt"
    local  statusBefore="$( git status --short )"
    popd  > /dev/null

    #// Main
    "${LocommitCommand}" clone "_testing/repository" "_testing/a/work"  &&  Error

    #// Check
    AssertNotExist  "_testing/a/work"
    pushd  "_testing/repository"  > /dev/null
    local  status="$( git status --short )"
    popd  > /dev/null
    if [ "${status}" != "${statusBefore}" ]; then  Error  ;fi
    DeleteFolder  "_testing"
}

function  Test_InWorkingDirectory() {
    echo  ""
    echo  "### Test_InWorkingDirectory"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    echo "x" > "_testing/build/out"
    echo "x" > "_testing/example.txt"
    echo "build"      > "_testing/.gitignore"
    echo ".commit"   >> "_testing/.gitignore"
    echo ".commit_*" >> "_testing/.gitignore"

    pushd "_testing" > /dev/null
    git init ${GitInitOption}  > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "."  > /dev/null  2>&1
    git commit  -m "temporary"  > /dev/null  2>&1
    AssertExist  ".git"

    "../${LocommitCommand}"  &&  TestError
    "../${LocommitCommand}" --no-git  ||  TestError
    AssertExist  ".git"
    popd > /dev/null

    AssertExist        "_testing/.commit/example.txt"
    AssertExist        "_testing/.commit/.gitignore"
    AssertNotExist     "_testing/.commit/build"
    AssertNotExist     "_testing/.commit/build/out"
    AssertNotReadOnly  "_testing/.commit/example.txt"
    AssertNotReadOnly  "_testing/.commit/.gitignore"
    DeleteFolder  "_testing"
}

function  Test_InWorkingSubDirectory() {
    echo  ""
    echo  "### Test_InWorkingSubDirectory"
    DeleteFolder  "_testing"
    mkdir -p "_testing/sub/build"
    echo "x" > "_testing/sub/build/out"
    echo "x" > "_testing/sub/example.txt"
    echo "build" > "_testing/sub/.gitignore"

    pushd "_testing" > /dev/null
    git init ${GitInitOption}  > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "."  > /dev/null  2>&1
    git commit  -m "temporary"  > /dev/null  2>&1
    cd  "sub"

    "../../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertExist     "_testing/.git"
    AssertExist     "_testing/sub/.git"
    AssertExist     "_testing/sub/.commit/example.txt"
    AssertExist     "_testing/sub/.commit/.gitignore"
    AssertNotExist  "_testing/sub/.commit/build"
    AssertNotExist  "_testing/sub/.commit/build/out"
    AssertReadOnly  "_testing/sub/.commit/example.txt"
    AssertReadOnly  "_testing/sub/.commit/.gitignore"

    #// Check if no error of submodule, when git add is run.
    rm -rf  "_testing/sub/.git"
    echo  "a" >  "_testing/sub/a"
    pushd "_testing" > /dev/null
    echo  "git status"
    if git status --short | grep 'sub/a'; then  : ;  else  TestError  ;fi
    echo  "git add ."

    git add "."  ||  TestError
    popd > /dev/null
    DeleteFolder  "_testing"
}

function  Test_NoUpdate() {  #// Base test is "Test_1"
    echo  ""
    echo  "### Test_NoUpdate"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    mkdir -p "_testing/.commit"
    echo "x"       > "_testing/example.txt"
    echo "x"       > "_testing/build/out"
    echo ".commit" > "_testing/.gitignore"
    echo "build"  >> "_testing/.gitignore"
    echo "x"       > "_testing/.commit/example.txt"
    echo ".commit" > "_testing/.commit/.gitignore"
    echo "build"  >> "_testing/.commit/.gitignore"

    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertNotExist  "_testing/.commit_new/"

    AssertExist     "_testing/.commit/example.txt"
    AssertExist     "_testing/.commit/.gitignore"
    AssertNotExist  "_testing/.commit/.commit"
    AssertNotExist  "_testing/.commit/build"
    AssertNotExist  "_testing/.commit/build/out"
    DeleteFolder  "_testing"
}

function  Test_NoModifiedConflict() {  #// Base test is "Test_1"
    echo  ""
    echo  "### Test_NoModifiedConflict"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    echo "x" > "_testing/build/out"
    echo "x"                   > "_testing/example.txt"
    echo "<<<<<<< HEAD"       >> "_testing/example.txt"
    echo "    my edit"        >> "_testing/example.txt"
    echo "======="            >> "_testing/example.txt"
    echo "    others edit"    >> "_testing/example.txt"
    echo ">>>>>>> __Others__" >> "_testing/example.txt"
    echo "build"      > "_testing/.gitignore"
    echo ".commit"   >> "_testing/.gitignore"
    echo ".commit_*" >> "_testing/.gitignore"

    AssertNotExist  "_testing/.commit"

    echo  "$ locommit"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null
    AssertExist  "_testing/.commit"

    echo  "$ locommit"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError  #// 2nd execute
    popd > /dev/null
    AssertExist     "_testing/.commit"
    AssertNotExist  "_testing/.commit_new"

    DeleteFolder  "_testing"
}

function  Test_NoGitOption() {
    echo  ""
    echo  "### Test_NoGitOption"

    #// .git folder
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    echo "x" > "_testing/build/out"
    echo "x" > "_testing/example.txt"
    echo "build"      > "_testing/.gitignore"
    echo ".commit"   >> "_testing/.gitignore"
    echo ".commit_*" >> "_testing/.gitignore"

    pushd "_testing" > /dev/null
    git init ${GitInitOption}  > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "."  > /dev/null  2>&1
    git commit  -m "temporary"  > /dev/null  2>&1
    AssertExist  ".git"

    "../${LocommitCommand}" --no-git  ||  TestError
    popd > /dev/null
    AssertExist  "_testing/.commit"
    AssertExist  "_testing/.commit/example.txt"

    #// without .git folder
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    echo "x" > "_testing/build/out"
    echo "x" > "_testing/example.txt"
    echo "build"      > "_testing/.gitignore"
    echo ".commit"   >> "_testing/.gitignore"
    echo ".commit_*" >> "_testing/.gitignore"
    pushd "_testing" > /dev/null

    "../${LocommitCommand}" --no-git  ||  TestError
    popd > /dev/null
    AssertExist     "_testing/.commit"
    AssertExist     "_testing/.commit/example.txt"
    AssertNotExist  "_testing/.git"
    DeleteFolder  "_testing"
}

function  Test_Diff() {  #// Base test is "Test_1"
    echo  ""
    echo  "### Test_Diff"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    mkdir -p "_testing/.commit"
    echo "x"       > "_testing/example.txt"
    echo "x"       > "_testing/build/out"
    echo ".commit" > "_testing/.gitignore"
    echo "build"  >> "_testing/.gitignore"
    echo "2"       > "_testing/.commit/example.txt"

    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertExist     "_testing/.commit/example.txt"
    AssertNotExist  "_testing/.commit/.gitignore"

    AssertExist     "_testing/.commit_new/example.txt"
    AssertExist     "_testing/.commit_new/.gitignore"
    AssertNotExist  "_testing/.commit_new/.commit"
    AssertNotExist  "_testing/.commit_new/build"
    AssertNotExist  "_testing/.commit_new/build/out"
    DeleteFolder  "_testing"
}

function  Test_Diff_InWorkingDirectory() {  #// Base test is "Test_Diff" and "Test_InWorkingDirectory"
    echo  ""
    echo  "### Test_Diff_InWorkingDirectory"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    mkdir -p "_testing/.commit"
    echo "x"       > "_testing/example.txt"
    echo "x"       > "_testing/build/out"
    echo ".commit" > "_testing/.gitignore"
    echo "build"  >> "_testing/.gitignore"
    echo "2"       > "_testing/.commit/example.txt"

    pushd "_testing" > /dev/null
    git init ${GitInitOption}  > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "."  > /dev/null  2>&1
    git commit  -m "temporary"  > /dev/null  2>&1

    "../${LocommitCommand}"  ||  TestError
    AssertExist  ".git"
    popd > /dev/null

    AssertExist     "_testing/.commit/example.txt"
    AssertNotExist  "_testing/.commit/.gitignore"

    AssertExist     "_testing/.commit_new/example.txt"
    AssertExist     "_testing/.commit_new/.gitignore"
    AssertNotExist  "_testing/.commit_new/.commit"
    AssertNotExist  "_testing/.commit_new/build"
    AssertNotExist  "_testing/.commit_new/build/out"
    DeleteFolder  "_testing"
}

function  Test_Diff_InWorkingSubDirectory() {  #// Base test is "Test_Diff_InWorkingDirectory" and "Test_InWorkingSubDirectory"
    echo  ""
    echo  "### Test_Diff_InWorkingSubDirectory"
    DeleteFolder  "_testing"
    mkdir -p "_testing/sub/build"
    mkdir -p "_testing/sub/.commit"
    echo "x"       > "_testing/sub/example.txt"
    echo "x"       > "_testing/sub/build/out"
    echo ".commit" > "_testing/sub/.gitignore"
    echo "build"  >> "_testing/sub/.gitignore"
    echo "2"       > "_testing/sub/.commit/example.txt"

    pushd "_testing" > /dev/null
    git init ${GitInitOption}  > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "."  > /dev/null  2>&1
    git commit  -m "temporary"  > /dev/null  2>&1
    cd  "sub"

    "../../${LocommitCommand}"  ||  TestError
    cd  ".."
    AssertExist  ".git"
    popd > /dev/null

    AssertExist     "_testing/sub/.commit/example.txt"
    AssertNotExist  "_testing/sub/.commit/.gitignore"

    AssertExist     "_testing/sub/.commit_new/example.txt"
    AssertExist     "_testing/sub/.commit_new/.gitignore"
    AssertNotExist  "_testing/sub/.commit_new/.commit"
    AssertNotExist  "_testing/sub/.commit_new/build"
    AssertNotExist  "_testing/sub/.commit_new/build/out"
    DeleteFolder  "_testing"
}

function  Test_Push_1() {
    echo  ""
    echo  "### Test_Push_1"
    DeleteFolder  "_testing"
    MakePushTestFiles
    echo "del" > "_testing/will_delete.txt"

    pushd "_testing" > /dev/null

    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError

    echo "after" > "example.txt"
    echo "new" > "new X.txt"
    rm  "will_delete.txt"

    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError

    echo  "$ locommit push _repository"
    "../${LocommitCommand}" push "_repository"  ||  TestError

    popd > /dev/null

    AssertNotExist  "_testing/.commit_new"

    AssertExist     "_testing/.commit/example.txt"
    AssertExist     "_testing/.commit/new X.txt"
    AssertExist     "_testing/.commit/.gitignore"
    AssertNotExist  "_testing/.commit/build"
    AssertNotExist  "_testing/.commit/build/out"
    AssertReadOnly  "_testing/.commit/example.txt"
    AssertReadOnly  "_testing/.commit/new X.txt"
    AssertReadOnly  "_testing/.commit/.gitignore"
    AssertContents  "_testing/new X.txt"  'new\n'

    AssertExist        "_testing/_repository/example.txt"
    AssertExist        "_testing/_repository/new X.txt"
    AssertExist        "_testing/_repository/.gitignore"
    AssertExist        "_testing/_repository/.git"
    AssertExist        "_testing/_repository/old_files"
    AssertNotExist     "_testing/_repository/build"
    AssertNotExist     "_testing/_repository/build/out"
    AssertNotReadOnly  "_testing/_repository/example.txt"
    AssertNotReadOnly  "_testing/_repository/new X.txt"
    AssertNotReadOnly  "_testing/_repository/.gitignore"

    local  gitStatus="$(cd _testing  &&  GitStatusCurrentFolder)"
    if [ "${gitStatus}" != "?? ./" ]; then  #// Case of parent .git does not check any status.
        if [ "${gitStatus}" != "" ]; then  TestError;  fi
    fi
    DeleteFolder  "_testing"
}

function  Test_Push_NoCommitNewNoDiff() {
    echo  ""
    echo  "### Test_Push_NoCommitNewNoDiff"
    DeleteFolder  "_testing"
    MakePushTestFiles

    pushd "_testing" > /dev/null
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    AssertExist     ".commit"
    AssertNotExist  ".commit_new"

    echo  "$ locommit push _repository"
    "../${LocommitCommand}" push "_repository"  ||  TestError
    popd > /dev/null

    AssertExist        "_testing/_repository/example.txt"
    AssertNotReadOnly  "_testing/_repository/example.txt"
    DeleteFolder  "_testing"
}

function  Test_Push_NoCommitError() {
    echo  ""
    echo  "### Test_Push_NoCommitError"
    #// Error test of no .commit_new but different contents
    DeleteFolder  "_testing"
    MakePushTestFiles

    pushd "_testing" > /dev/null
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError

    rm  "example.txt"
    AssertExist     ".commit"
    AssertNotExist  ".commit_new"

    echo  "$ locommit push _repository"
    "../${LocommitCommand}" push "_repository"
    local  exitCode=$?
    popd > /dev/null

    if [ "${exitCode}" == "0" ]; then
        TestError  "Failed"
    fi
    AssertNotExist  "_testing/_repository/example.txt"
    DeleteFolder  "_testing"
}

function  Test_Push_Null() {
    echo  ""
    echo  "### Test_Push_Null"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"     > "_testing/.gitignore"
    echo ".commit_*"  >> "_testing/.gitignore"
    mkdir -p "_testing/build"

    echo "a"  > "_testing/example.txt"
    echo "b" >> "_testing/example.txt"
    echo "c" >> "_testing/example.txt"

    pushd "_testing" > /dev/null

    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null
    AssertExist     "_testing/.commit"
    AssertNotExist  "_testing/.commit_new"

    echo "a new"  > "_testing/example.txt"
    echo "b"     >> "_testing/example.txt"
    echo "c"     >> "_testing/example.txt"

    pushd "_testing" > /dev/null

    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null
    AssertExist  "_testing/.commit_new"

    echo  "$ locommit push /dev/null"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}" push "/dev/null"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/example.txt"  'a new\nb\nc\n'
    AssertNotExist  "_testing/.commit_new"
    AssertExist     "_testing/.commit"
    AssertContents  "_testing/.commit/example.txt"  'a new\nb\nc\n'
    DeleteFolder  "_testing"
}

function  Test_Push_RemovedFiles() {
    echo ""
    echo "Test_Push_RemovedFiles"

    #// Set up
        DeleteFolder  "_testing"

        #// Make a "repository" folder
        mkdir -p  "_testing/repository/sub"
        echo ".commit"     > "_testing/repository/.gitignore"
        echo ".commit_*"  >> "_testing/repository/.gitignore"
        echo "x" > "_testing/repository/x"
        echo "y" > "_testing/repository/y"
        echo "x" > "_testing/repository/sub/x"
        echo "y" > "_testing/repository/sub/y"

        #// Make a "working" and ".commit" folder
        echo  "$ locommit clone"
        "${LocommitCommand}" clone  "_testing/repository"  "_testing/working"  ||  TestError

        #// Make a ".commit_new" folder
        rm  "_testing/working/x"
        rm  "_testing/working/sub/y"
        echo  "updated"  >  "_testing/working/y"
        pushd "_testing/working" > /dev/null
        echo  "$ locommit"
        "../../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        #// Add other files to "repository" folder
        echo "z" > "_testing/repository/z"
        echo "z" > "_testing/repository/sub/z"

    #// Main
    pushd "_testing/working" > /dev/null
    echo  "$ locommit push"
    "../../${LocommitCommand}" push  "../repository"  ||  TestError
    popd > /dev/null

    #// Check
    AssertNotExist  "_testing/repository/x"
    AssertExist     "_testing/repository/y"
    AssertExist     "_testing/repository/sub/x"
    AssertNotExist  "_testing/repository/sub/y"
    AssertExist     "_testing/repository/z"
    AssertExist     "_testing/repository/sub/z"
    if [ "$( cat "_testing/repository/y" )" != "updated" ]; then  TestError  ;fi
    DeleteFolder  "_testing"
}

function  Test_Push_SameOrParentFolderError() {
    echo ""
    echo "Test_Push_SameOrParentFolderError"

    #// Set up
        DeleteFolder  "_testing"
        mkdir -p "_testing/main"
        echo ".commit"     > "_testing/main/.gitignore"
        echo ".commit_*"  >> "_testing/main/.gitignore"
        echo "x" > "_testing/main/x"

        #// Make a ".commit" folder
        pushd "_testing/main" > /dev/null
        echo  "$ locommit"
        "../../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        #// Make a ".commit_new" folder
        echo "x2" > "_testing/main/x"
        pushd "_testing/main" > /dev/null
        echo  "$ locommit"
        "../../${LocommitCommand}"  ||  TestError
        popd > /dev/null

    #// push command to same folder. This command will be occurred an error
    pushd "_testing/main" > /dev/null
    echo  "$ locommit push ."
    "../../${LocommitCommand}" push "."
    local  exitCode="$?"
    popd > /dev/null
    if [ "${exitCode}" == "0" ]; then  TestError  ;fi

    #// push command to parent folder. This command will be occurred an error
    pushd "_testing/main" > /dev/null
    echo  "$ locommit push .."
    "../../${LocommitCommand}" push ".."
    local  exitCode="$?"
    popd > /dev/null
    if [ "${exitCode}" == "0" ]; then  TestError  ;fi
    DeleteFolder  "_testing"
}

function  Test_Pull_1() {
    echo  ""
    echo  "### Test_Pull_1"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    mkdir -p "_testing/build"

    echo "x"  > "_testing/build/out"
    echo "a"  > "_testing/example.txt"
    echo "b" >> "_testing/example.txt"
    echo "c" >> "_testing/example.txt"

    mkdir -p "_testing/_repository"
    cp  "_testing/.gitignore"  "_testing/_repository/.gitignore"
    echo "a"      > "_testing/_repository/example.txt"
    echo "b"     >> "_testing/_repository/example.txt"
    echo "c new" >> "_testing/_repository/example.txt"

    #// pull command
    pushd "_testing" > /dev/null

    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError

    echo  "$ locommit pull _repository"
    "../${LocommitCommand}" pull "_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/example.txt"  'a\nb\nc new\n'
    AssertExist     "_testing/.commit_ours"
    AssertExist     "_testing/.commit_theirs"
    AssertNotExist  "_testing/.commit_new"
    AssertExist     "_testing/.commit"

    #// push command
    pushd "_testing" > /dev/null
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertExist  "_testing/.commit_new"

    pushd "_testing" > /dev/null
    echo  "$ locommit push _repository"
    "../${LocommitCommand}" push "_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/_repository/example.txt"  'a\nb\nc new\n'
    AssertNotExist  "_testing/.commit_ours"
    AssertNotExist  "_testing/.commit_theirs"
    AssertNotExist  "_testing/.commit_new"
    DeleteFolder  "_testing"
}

function  Test_Pull_NoInput() {  #// Base test is "Test_Pull_1"
    echo  ""
    echo  "### Test_Pull_NoInput"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    mkdir -p "_testing/build"

    echo "x"  > "_testing/build/out"
    echo "a"  > "_testing/example.txt"
    echo "b" >> "_testing/example.txt"
    echo "c" >> "_testing/example.txt"

    mkdir -p "_testing/_repository"
    cp  "_testing/.gitignore"  "_testing/_repository/.gitignore"
    echo "a"  > "_testing/_repository/example.txt"
    echo "b" >> "_testing/_repository/example.txt"
    echo "c" >> "_testing/_repository/example.txt"

    pushd "_testing/_repository" > /dev/null
    git init ${GitInitOption} > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "." > /dev/null
    git commit -m "1st" > /dev/null
    popd > /dev/null

    #// pull command
    echo  "$ locommit"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null
    AssertContents  "_testing/.commit/example.txt"  'a\nb\nc\n'

    echo "a"      > "_testing/example.txt"
    echo "b"     >> "_testing/example.txt"
    echo "c new" >> "_testing/example.txt"

    echo  "$ locommit"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null
    AssertContents  "_testing/.commit/example.txt"      'a\nb\nc\n'
    AssertContents  "_testing/.commit_new/example.txt"  'a\nb\nc new\n'

    echo  "$ locommit pull _repository"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}" pull "_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/example.txt"  'a\nb\nc new\n'
    AssertNotExist  "_testing/.commit_ours"
    AssertNotExist  "_testing/.commit_theirs"
    AssertContents  "_testing/.commit/example.txt"      'a\nb\nc\n'
    AssertContents  "_testing/.commit_new/example.txt"  'a\nb\nc new\n'

    #// second pull command (It requests no error)
    echo  "$ locommit pull _repository"
    pushd "_testing" > /dev/null
    "../${LocommitCommand}" pull "_repository"
    local  exitCode=$?
    local  branches="$( git branch )"
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/example.txt"  'a\nb\nc new\n'
    AssertNotExist  "_testing/.commit_ours"
    AssertNotExist  "_testing/.commit_theirs"
    AssertContents  "_testing/.commit/example.txt"      'a\nb\nc\n'
    AssertContents  "_testing/.commit_new/example.txt"  'a\nb\nc new\n'
    echo "${branches}" | grep " __locommit_commit_theirs$"  &&  TestError

    #// push command
    pushd "_testing" > /dev/null
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertExist  "_testing/.commit_new"

    pushd "_testing" > /dev/null
    echo  "$ locommit push _repository"
    "../${LocommitCommand}" push "_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/_repository/example.txt"  'a\nb\nc new\n'
    AssertContents  "_testing/.commit/example.txt"      'a\nb\nc new\n'
    AssertNotExist  "_testing/.commit_ours"
    AssertNotExist  "_testing/.commit_theirs"
    AssertNotExist  "_testing/.commit_new"
    DeleteFolder  "_testing"
}

function  Test_Pull_Merge() {
    echo  ""
    echo  "### Test_Pull_Merge"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    mkdir -p "_testing/build"

    echo "x" > "_testing/build/out"
    echo "a"  > "_testing/example.txt"
    echo "b" >> "_testing/example.txt"
    echo "c" >> "_testing/example.txt"

    mkdir -p "_testing/_repository"
    cp  "_testing/.gitignore"  "_testing/_repository/.gitignore"
    echo "a"      > "_testing/_repository/example.txt"
    echo "b"     >> "_testing/_repository/example.txt"
    echo "c new" >> "_testing/_repository/example.txt"
    pushd "_testing/_repository" > /dev/null
    git init ${GitInitOption} > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "." > /dev/null
    git commit -m "1st" > /dev/null
    popd > /dev/null

    #// pull command
        pushd "_testing" > /dev/null

        echo  "$ locommit"
        "../${LocommitCommand}"  ||  TestError

        echo "a new" > "example.txt"
        echo "b"    >> "example.txt"
        echo "c"    >> "example.txt"

        echo  "$ locommit pull _repository"
        "../${LocommitCommand}" pull "_repository"
        local  exitCode=$?
        popd > /dev/null
        if [ "${exitCode}" != "0" ]; then
            TestError  "Failed"
        fi

        AssertContents  "_testing/example.txt"  'a new\nb\nc new\n'
        AssertExist     "_testing/.commit_ours"
        AssertExist     "_testing/.commit_theirs"
        AssertNotExist  "_testing/.commit_new"
        AssertExist     "_testing/.commit"

    #// push command
        pushd "_testing" > /dev/null
        echo  "$ locommit"
        "../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        AssertExist  "_testing/.commit_new"

        pushd "_testing" > /dev/null
        echo  "$ locommit push _repository"
        "../${LocommitCommand}" push "_repository"
        local  exitCode=$?
        popd > /dev/null
        if [ "${exitCode}" != "0" ]; then
            TestError  "Failed"
        fi

        AssertContents  "_testing/_repository/example.txt"  'a new\nb\nc new\n'
        AssertNotExist  "_testing/.commit_new"
        AssertNotExist  "_testing/.commit_ours"
        AssertNotExist  "_testing/.commit_theirs"
    DeleteFolder  "_testing"
}

function  Test_Pull_Conflict() {
    echo  ""
    echo  "### Test_Pull_Conflict"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    echo ".DS_Store"   >> "_testing/.gitignore"
    mkdir -p "_testing/build"
    mkdir -p "_testing/_repository/build"

    echo "x" > "_testing/build/out"
    echo "a"  > "_testing/example.txt"
    echo "b" >> "_testing/example.txt"
    echo "c" >> "_testing/example.txt"
    echo "in work" > "_testing/build/ignore.txt"  #// ignore test case

    cp  "_testing/.gitignore"  "_testing/_repository/.gitignore"
    echo "a"      > "_testing/_repository/example.txt"
    echo "b"     >> "_testing/_repository/example.txt"
    echo "c new" >> "_testing/_repository/example.txt"
    echo "in rep" > "_testing/_repository/build/ignore.txt"  #// ignore test case
    pushd "_testing/_repository" > /dev/null
    git init ${GitInitOption} > /dev/null  2>&1
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    git add "." > /dev/null
    git commit -m "1st" > /dev/null
    popd > /dev/null

    #// pull command
        pushd "_testing" > /dev/null

        echo  "$ locommit"
        "../${LocommitCommand}"  ||  TestError

        echo "a"             > "example.txt"
        echo "b"            >> "example.txt"
        echo "c conflicted" >> "example.txt"

        echo  "$ locommit"
        "../${LocommitCommand}"  ||  TestError

        echo  "$ locommit pull _repository"
        "../${LocommitCommand}" pull "_repository"
        local  exitCode=$?
        popd > /dev/null
        if [ "${exitCode}" != "0" ]; then
            TestError  "Failed"
        fi

        #// Check conflict status
        AssertContents  "_testing/.commit/example.txt"  'a\nb\nc\n'
        AssertContents  "_testing/.commit_ours/example.txt"  'a\nb\nc conflicted\n'
        AssertContents  "_testing/.commit_theirs/example.txt"   'a\nb\nc new\n'
        grep  "<<<<<<<"  "_testing/example.txt"  > /dev/null  ||  TestError  #// Expected confilcts
        local  result="$(cd _testing  &&  git status --short)"
        echo "${result}" | grep "^UU example.txt$"  > /dev/null  ||  TestError  #// Expected both modified
        AssertExist     "_testing/.commit_ours"
        AssertExist     "_testing/.commit_theirs"
        AssertNotExist  "_testing/.commit_new"
        AssertNotExist  "_testing/.commit_theirs/build/ignore.txt"

    #// Still conflicted (locommit command)
        pushd "_testing" > /dev/null
            echo  "$ locommit"
            "../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        AssertContents  "_testing/example.txt"  'a\nb\n<<<<<<< HEAD\nc conflicted\n=======\nc new\n>>>>>>> __locommit_commit_theirs\n'
        AssertExist  "_testing/.commit_ours"
        AssertExist  "_testing/.commit_theirs"
        AssertExist  "_testing/.commit_new"

    #// Resolve conflicts (locommit command)
        pushd "_testing" > /dev/null
            echo "a"         > "example.txt"
            echo "b"        >> "example.txt"
            echo "c merged" >> "example.txt"
            echo  "Resolved."

            echo  "$ locommit"
            "../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        AssertContents  "_testing/example.txt"  'a\nb\nc merged\n'
        AssertExist  "_testing/.commit_ours"
        AssertExist  "_testing/.commit_theirs"
        AssertExist  "_testing/.commit_new"
        AssertContents  "_testing/build/ignore.txt"  "in work"
 
    #// push command
        pushd "_testing" > /dev/null
            echo  "$ locommit push _repository"
            "../${LocommitCommand}" push "_repository" ||  TestError
        popd > /dev/null

        AssertContents  "_testing/_repository/example.txt"  'a\nb\nc merged\n'
        AssertContents  "_testing/_repository/build/ignore.txt"  "in rep"
        AssertNotExist  "_testing/.commit_ours"
        AssertNotExist  "_testing/.commit_theirs"
        AssertNotExist  "_testing/.commit_new"
    DeleteFolder  "_testing"
}

function  Test_Pull_IgnoreInRepository() {  #// Base test is "Test_Pull_1"
    echo  ""
    echo  "### Test_Pull_IgnoreInRepository"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing/working"
    echo ".commit"      > "_testing/working/.gitignore"
    echo ".commit_*"   >> "_testing/working/.gitignore"
    echo "_repository" >> "_testing/working/.gitignore"
    echo "build"       >> "_testing/working/.gitignore"
    mkdir -p "_testing/working/build"

    echo "x"  > "_testing/working/build/out"
    echo "a"  > "_testing/working/example.txt"
    echo "b" >> "_testing/working/example.txt"
    echo "c" >> "_testing/working/example.txt"

    mkdir -p "_testing/_repository/build"
    cp  "_testing/working/.gitignore"  "_testing/_repository/.gitignore"
    echo "a"      > "_testing/_repository/example.txt"
    echo "b"     >> "_testing/_repository/example.txt"
    echo "c new" >> "_testing/_repository/example.txt"
    echo "in rep" > "_testing/_repository/build/ignore.txt"  #// Main test file

    #// pull command
    pushd "_testing/working" > /dev/null

    echo  "$ locommit"
    "../../${LocommitCommand}"  ||  TestError

    echo  "$ locommit pull _repository"
    "../../${LocommitCommand}" pull "../_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/working/example.txt"  'a\nb\nc new\n'
    AssertExist     "_testing/working/.commit_ours"
    AssertExist     "_testing/working/.commit_theirs"
    AssertNotExist  "_testing/working/.commit_new"
    AssertExist     "_testing/working/.commit"
    AssertNotExist  "_testing/working/.commit_theirs/build"

    #// push command
    pushd "_testing/working" > /dev/null
    echo  "$ locommit"
    "../../${LocommitCommand}"  ||  TestError
    popd > /dev/null

    AssertExist  "_testing/working/.commit_new"

    pushd "_testing/working" > /dev/null
    echo  "$ locommit push _repository"
    "../../${LocommitCommand}" push "../_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/_repository/example.txt"  'a\nb\nc new\n'
    AssertContents  "_testing/_repository/build/ignore.txt"  "in rep"
    AssertNotExist  "_testing/working/.commit_ours"
    AssertNotExist  "_testing/working/.commit_theirs"
    AssertNotExist  "_testing/working/.commit_new"
    DeleteFolder  "_testing"
}

function  Test_Pull_Push_InWorkingSubDirectory() {
    echo  ""
    echo  "### Test_Pull_Push_InWorkingSubDirectory"

    #// Set up
        DeleteFolder  "_testing"

        mkdir -p "_testing"
        pushd  "_testing"  > /dev/null
        git init ${GitInitOption}  > /dev/null
        git config --local user.email "${LocommitEMail}"
        git config --local user.name  "${LocommitUser}"
        AssertExist  ".git"
        echo ".commit"       > ".gitignore"
        echo ".commit_*"    >> ".gitignore"
        echo "/example.txt" >> ".gitignore"

        mkdir -p "project"
        pushd  "project"  > /dev/null
        echo "1" > "example.txt"
        git add ".."
        git commit -m "1st"  > /dev/null
        echo "2" > "example.txt"

        #// Set up a modified git state
        local  result=$( git status --short )
        if [ "${result}" != "$( echo -e ' M example.txt\n' )" ]; then
            TestError
        fi
        popd  > /dev/null
        popd  > /dev/null

    #// locommit command
    pushd  "_testing/project"  > /dev/null
    echo  "$ locommit"
    "../../${LocommitCommand}"  ||  TestError
    echo  "$ locommit"  #// 2nd executing
    "../../${LocommitCommand}"  ||  TestError
    popd  > /dev/null
    AssertExist     "_testing/project/.commit"
    AssertNotExist  "_testing/project/.commit_new"

    #// pull command
    mkdir -p   "_testing/repository"
    echo "r" > "_testing/repository/example.txt"
    pushd  "_testing/project"  > /dev/null

    echo  "$ locommit pull ../repository"
    "../../${LocommitCommand}" pull "../repository"  ||  TestError
    popd  > /dev/null
    AssertContents  "_testing/project/.commit/example.txt"  '2\n'
    AssertContents  "_testing/project/.commit_ours/example.txt"  '2\n'
    AssertContents  "_testing/project/.commit_theirs/example.txt"   'r\n'
    DeleteFolder  "_testing"
}

function  Test_Pull_Push_TargetInWorkingDirectory() {
    echo ""
    echo "### Test_Pull_Push_TargetInWorkingDirectory"

    #// Set up
    DeleteFolder  "_testing"

    mkdir -p "_testing/_repository"
    pushd  "_testing/_repository"  > /dev/null
    git init ${GitInitOption}  > /dev/null
    git config --local user.email "${LocommitEMail}"
    git config --local user.name  "${LocommitUser}"
    AssertExist  ".git"
    echo  ".commit"      > ".gitignore"
    echo  ".commit_*"   >> ".gitignore"
    echo  "_repository" >> ".gitignore"
    echo  "a"  > "example.txt"
    echo  "b" >> "example.txt"
    echo  "c" >> "example.txt"
    git add "."  > /dev/null
    git commit -m "First commit."  > /dev/null
    popd  > /dev/null
    AssertExist  "_testing/_repository/example.txt"

    pushd  "_testing"  > /dev/null
    CopyFolder  "_repository"  "."
    popd  > /dev/null
    AssertExist  "_testing/example.txt"

    #// Error of making new ".commit" folder, if ".git" folder exists
    pushd  "_testing"  > /dev/null
    echo  "$ locommit"
    "../${LocommitCommand}"  &&  TestError
    popd  > /dev/null
    AssertNotExist  "_testing/.commit"

    #// Make a ".commit" folder
    pushd  "_testing"  > /dev/null
    echo  "$ rm -rf .git"
    rm -rf  ".git"
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd  > /dev/null
    AssertExist  "_testing/.commit"

    #// Add a commit in reposiroty
    pushd  "_testing/_repository"  > /dev/null
    echo  "[_reporitory]$ git commit"
    echo  "a"      > "example.txt"
    echo  "b"     >> "example.txt"
    echo  "c new" >> "example.txt"
    git add "."  > /dev/null
    git commit -m "Second commit."  > /dev/null
    popd  > /dev/null

    #// Make ".commit_new" folder
    pushd  "_testing"  > /dev/null
    echo  "$ edit"
    echo  "a new"  > "example.txt"
    echo  "b"     >> "example.txt"
    echo  "c"     >> "example.txt"
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd  > /dev/null
    AssertExist  "_testing/.commit_new"

    #// Pull command
    pushd  "_testing"  > /dev/null
    echo  "$ locommit pull _repository"
    "../${LocommitCommand}" pull  "_repository"  ||  TestError
    popd  > /dev/null
    AssertContents  "_testing/.commit_ours/example.txt"  'a new\nb\nc\n'
    AssertContents  "_testing/.commit_theirs/example.txt"  'a\nb\nc new\n'
    AssertContents  "_testing/example.txt"  'a new\nb\nc new\n'
    AssertNotExist  "_testing/.commit_new"

    #// Make ".commit" folder
    pushd  "_testing"  > /dev/null
    echo  "$ locommit"
    "../${LocommitCommand}"  ||  TestError
    popd  > /dev/null
    AssertContents  "_testing/.commit_ours/example.txt"  'a new\nb\nc\n'
    AssertContents  "_testing/.commit_theirs/example.txt"  'a\nb\nc new\n'
    AssertContents  "_testing/example.txt"  'a new\nb\nc new\n'
    AssertContents  "_testing/.commit_new/example.txt"  'a new\nb\nc new\n'

    #// Push command
    pushd  "_testing"  > /dev/null
    echo  "$ locommit push _repository"
    "../${LocommitCommand}" push  "_repository"  ||  TestError
    popd  > /dev/null
    AssertNotExist  "_testing/.commit_ours"
    AssertNotExist  "_testing/.commit_theirs"
    AssertNotExist  "_testing/.commit_new"

    #// Check if the reporitory is not added a commit
    local  result="$(cd _testing/_repository  &&  git diff)"
    echo  "${result}" | grep "\-a"      > /dev/null  ||  TestError
    echo  "${result}" | grep  "+a new"  > /dev/null  ||  TestError
    DeleteFolder  "_testing"
}

function  Test_PullBase_1() {  #// Base test is "Test_Pull_1"
    echo ""
    echo "### Test_PullBase_1"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    mkdir -p "_testing/build"
    mkdir -p "_testing/_base"

    echo "x"      > "_testing/build/out"
    echo "a"      > "_testing/example.txt"
    echo "b"      > "_testing/_base/base_update.txt"
    echo "w"      > "_testing/_base/work_update.txt"
    AssertNotExist  "_testing/_base/_base/work_update.txt"
    echo "b"      > "_testing/base_update.txt"
    echo "w"      > "_testing/work_update.txt"

    mkdir -p "_testing/_repository/_base"
    echo "b new"  > "_testing/_repository/base_update.txt"
    echo "w"      > "_testing/_repository/work_update.txt"
    echo "b old"  > "_testing/_repository/_base/base_update.txt"
    echo "w old"  > "_testing/_repository/_base/work_update.txt"

    #// pull command
    pushd "_testing" > /dev/null

    echo  "$ locommit    #// make a .commit folder"
    "../${LocommitCommand}"  ||  TestError

    echo  "$ edit  work_update.txt"
    echo  "w new"  > "work_update.txt"

    echo  "$ locommit pull-base _base _repository"
    "../${LocommitCommand}" pull-base  "_base"  "_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/example.txt"  'a'
    AssertContents  "_testing/base_update.txt"  'b new'
    AssertContents  "_testing/work_update.txt"  'w new'
    AssertContents  "_testing/_base/base_update.txt"  'b new'
    AssertContents  "_testing/_base/work_update.txt"  'w'
    AssertExist     "_testing/.commit_old_ours"
    AssertExist     "_testing/.commit_old_base"
    AssertExist     "_testing/_base"
    AssertNotExist  "_testing/.commit_new"
    AssertExist     "_testing/.commit"
    DeleteFolder  "_testing"
}

function  Test_PullBase_NoInput() {  #// Base tests are "Test_PullBase_1" and "Test_Pull_NoInput"
    echo  ""
    echo  "### Test_PullBase_NoInput"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    mkdir -p "_testing/build"
    mkdir -p "_testing/_base"

    echo "x"      > "_testing/build/out"
    echo "a"      > "_testing/example.txt"
    echo "b"      > "_testing/_base/base_no_update.txt"
    echo "w"      > "_testing/_base/work_update.txt"
    AssertNotExist  "_testing/_base/_base/work_update.txt"
    echo "b"      > "_testing/base_no_update.txt"
    echo "w"      > "_testing/work_update.txt"

    mkdir -p "_testing/_repository/_base"
    echo "b"      > "_testing/_repository/base_no_update.txt"
    echo "w"      > "_testing/_repository/work_update.txt"
    echo "b old"  > "_testing/_repository/_base/base_update.txt"
    echo "w old"  > "_testing/_repository/_base/work_update.txt"

    #// pull command
    pushd "_testing" > /dev/null

    echo  "$ locommit    #// make a .commit folder"
    "../${LocommitCommand}"  ||  TestError

    echo  "$ edit  work_update.txt"
    echo  "w new"  > "work_update.txt"

    echo  "$ locommit pull-base _base _repository"
    "../${LocommitCommand}" pull-base  "_base"  "_repository"
    local  exitCode=$?
    local  branches="$( git branch )"
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    AssertContents  "_testing/example.txt"  'a'
    AssertContents  "_testing/base_no_update.txt"  'b'
    AssertContents  "_testing/work_update.txt"  'w new'
    AssertContents  "_testing/_base/base_no_update.txt"  'b'
    AssertContents  "_testing/_base/work_update.txt"  'w'
    AssertNotExist  "_testing/.commit_old_ours"
    AssertNotExist  "_testing/.commit_old_base"
    AssertContents  "_testing/.commit_new/work_update.txt"  'w new'
    echo "${branches}" | grep " __locommit_commit_theirs$"  &&  TestError

    #// second pull command (It requests no error)
    pushd "_testing" > /dev/null

    echo  "$ locommit pull-base _base _repository"
    "../${LocommitCommand}" pull-base  "_base"  "_repository"
    local  exitCode=$?
    popd > /dev/null
    if [ "${exitCode}" != "0" ]; then
        TestError  "Failed"
    fi
    DeleteFolder  "_testing"
}

function  Test_PullBase_Conflict() {  #// Base tests are "Test_PullBase_1" and "Test_Pull_Conflict"
    echo  ""
    echo  "### Test_PullBase_Conflict"

    #// Set up
    DeleteFolder  "_testing"
    mkdir -p "_testing"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    echo ".DS_Store"   >> "_testing/.gitignore"
    mkdir -p "_testing/build"
    mkdir -p "_testing/_base2"
    mkdir -p "_testing/_repository/build"

    echo "x" > "_testing/build/out"
    echo "a"       > "_testing/example.txt"
    echo "b"       > "_testing/_base2/both_update.txt"
    echo "b now"   > "_testing/both_update.txt"
    echo "in work" > "_testing/build/ignore.txt"  #// ignore test case

    echo "in rep"  > "_testing/_repository/both_update.txt"
    echo "in rep"  > "_testing/_repository/build/ignore.txt"  #// ignore test case

    #// pull command
        pushd "_testing" > /dev/null

        echo  "$ locommit    #// make a .commit folder"
        "../${LocommitCommand}"  ||  TestError

        echo  "$ edit  both_update.txt"
        echo  "in work"  > "both_update.txt"

        echo  "$ locommit pull-base _base2 _repository"
        "../${LocommitCommand}" pull-base  "_base2"  "_repository"
        local  exitCode=$?
        popd > /dev/null
        if [ "${exitCode}" != "0" ]; then
            TestError  "Failed"
        fi

    #// Check conflict status
        AssertContents  "_testing/.commit/example.txt"  'a'
        AssertContents  "_testing/.commit_old_ours/both_update.txt"  'in work'
        AssertContents  "_testing/.commit_old_base/both_update.txt"  'b'
        AssertContents  "_testing/_base2/both_update.txt"  'in rep'
        grep  "<<<<<<<"  "_testing/both_update.txt"  > /dev/null  ||  TestError  #// Expected confilcts
        local  result="$(cd _testing  &&  git status --short)"
        echo "${result}" | grep "^UU both_update.txt$"  > /dev/null  ||  TestError  #// Expected both modified
        AssertExist     "_testing/.commit_old_ours"
        AssertExist     "_testing/.commit_old_base"
        AssertNotExist  "_testing/.commit_new"
        AssertNotExist  "_testing/_base2/build/ignore.txt"
        AssertExist     "_testing/build/ignore.txt"

    #// Still conflicted (locommit command)
        pushd "_testing" > /dev/null
            echo  "$ locommit"
            "../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        AssertContents  "_testing/both_update.txt"  '<<<<<<< HEAD\nin work\n=======\nin rep\n>>>>>>> __locommit_commit_theirs\n'
        AssertExist  "_testing/.commit_old_ours"
        AssertExist  "_testing/.commit_old_base"
        AssertExist  "_testing/.commit_new"

    #// Resolve conflicts (locommit command)
        pushd "_testing" > /dev/null
            echo "merged"  > "both_update.txt"
            echo  "Resolved."

            echo  "$ locommit"
            "../${LocommitCommand}"  ||  TestError
        popd > /dev/null

        AssertContents  "_testing/both_update.txt"  'merged'
        AssertContents  "_testing/_base2/both_update.txt"  "in rep"
        AssertExist  "_testing/.commit_old_ours"
        AssertExist  "_testing/.commit_old_base"
        AssertExist  "_testing/.commit_new"
        AssertContents  "_testing/build/ignore.txt"  "in work"

    #// push command
        pushd "_testing" > /dev/null
            mkdir -p  "_my_repository"
            echo  "$ locommit push _my_repository"
            "../${LocommitCommand}" push  "_my_repository"  ||  TestError
        popd > /dev/null

        AssertContents  "_testing/both_update.txt"  'merged'
        AssertContents  "_testing/.commit/both_update.txt"  'merged'
        AssertContents  "_testing/_my_repository/both_update.txt"  'merged'
        AssertContents  "_testing/_my_repository/_base2/both_update.txt"  "in rep"
        AssertNotExist  "_testing/.commit_old_ours"
        AssertNotExist  "_testing/.commit_old_base"
        AssertNotExist  "_testing/.commit_new"
    DeleteFolder  "_testing"
}

function  MakePushTestFiles() {
    mkdir -p "_testing/build"
    mkdir -p "_testing/_repository/.git"

    echo "x"            > "_testing/build/out"
    echo "x "           > "_testing/example.txt"
    echo ".commit"      > "_testing/.gitignore"
    echo ".commit_*"   >> "_testing/.gitignore"
    echo "build"       >> "_testing/.gitignore"
    echo "_repository" >> "_testing/.gitignore"
    echo "git"          > "_testing/_repository/.git/files"
    echo "old"          > "_testing/_repository/old_files"
}

function  Test_ResolvePath() {
    echo  ""
    echo  "### Test_ResolvePath"
    ResolvePath > /dev/null  #// Set "mnt_c" environmet variable
    if [ "$( ResolvePath "/mnt/c/" )" != "${mnt_c}/" ]; then  TestError;  fi
    if [ "$( ResolvePath "c:/" )"     != "${mnt_c}/" ]; then  TestError;  fi
    if [ "$( ResolvePath "/c/" )"     != "${mnt_c}/" ]; then  TestError;  fi
    if [ "$( ResolvePath "/home" )"   != "/home" ]; then  TestError;  fi
    if [ "$( ResolvePath "relative" )"      != "relative" ]; then  TestError;  fi
    if [ "$( ResolvePath "relative/path" )" != "relative/path" ]; then  TestError;  fi
    if [ "$( ResolvePath "/mnt/c/root-path" )" != "${mnt_c}/root-path" ]; then  TestError;  fi
    if [ "$( ResolvePath 'C:\' )"      != "${mnt_c}/" ]; then  TestError;  fi
    if [ "$( ResolvePath 'C:\Users' )" != "${mnt_c}/Users" ]; then  TestError;  fi
}

function  ResolvePath() {
    local  path_="$1"

    path_="$( echo "${path_}" | sed -e 's/\\/\//g' | sed -e 's/^C:/c:/' )"  #// replace to / and c:

    if [ "${mnt_c}" == "" ]; then
        export  mnt_c="/mnt/c";  if [ ! -e "/mnt/c" ]; then  export  mnt_c="c:"  ;fi
    fi
    if [ "${path_:0:3}" == "c:/"  -o  "${path_:0:3}" == "/c/" ]; then
        path_="${mnt_c}/${path_:3}"
    elif [ "${path_:0:7}" == "/mnt/c/" ]; then
        path_="${mnt_c}/${path_:7}"
    fi

    echo  "${path_}"
}

function  GetGitWorkingRootPath() {
    local  path="${PWD}"
    while [ "${path}" != "" ]; do

        if [ -e "${path}/.git" ]; then
            echo  "${path}"
            return
        fi
        path="${path%/*}" 
    done

    echo  ""
}

function  Test_CopyFolder() {
    echo  ""
    echo  "### Test_CopyFolder"
    DeleteFolder  "_testing"
    mkdir -p   "_testing/source"
    echo "x" > "_testing/source/a"
    echo "x" > "_testing/source/.a"
    echo "x" > "_testing/source/..a"
    mkdir -p   "_testing/source/node_modules/type"
    echo "x" > "_testing/source/node_modules/type/a"
    echo "x" > "_testing/source/node_modules/type/.a"
    echo "x" > "_testing/source/node_modules/type/..a"
    mkdir -p   "_testing/source/.vscode"
    echo "x" > "_testing/source/.vscode/a"
    echo "x" > "_testing/source/.vscode/.a"
    echo "x" > "_testing/source/.vscode/..a"
    mkdir -p   "_testing/source/.git"
    echo "x" > "_testing/source/.git/a"
    echo "x" > "_testing/source/.git/.a"
    echo "x" > "_testing/source/.git/..a"
    mkdir -p   "_testing/source/..d"
    echo "x" > "_testing/source/..d/a"
    echo "x" > "_testing/source/..d/.a"
    echo "x" > "_testing/source/..d/..a"

    CopyFolder  "_testing/source"  "_testing/destination"
    AssertExist  "_testing/destination/a"
    AssertExist  "_testing/destination/.a"
    AssertExist  "_testing/destination/..a"
    AssertExist  "_testing/destination/node_modules/type/a"
    AssertExist  "_testing/destination/node_modules/type/.a"
    AssertExist  "_testing/destination/node_modules/type/..a"
    AssertExist  "_testing/destination/.vscode/a"
    AssertExist  "_testing/destination/.vscode/.a"
    AssertExist  "_testing/destination/.vscode/..a"
    AssertExist  "_testing/destination/.git/a"
    AssertExist  "_testing/destination/.git/.a"
    AssertExist  "_testing/destination/.git/..a"
    AssertExist  "_testing/destination/..d/a"
    AssertExist  "_testing/destination/..d/.a"
    AssertExist  "_testing/destination/..d/..a"
    DeleteFolder  "_testing/destination"

    CopyFolder  "_testing/source"  "_testing/destination"  "--exclude=./.git"
    AssertExist  "_testing/destination/a"
    AssertExist  "_testing/destination/.a"
    AssertExist  "_testing/destination/..a"
    AssertExist  "_testing/destination/node_modules/type/a"
    AssertExist  "_testing/destination/node_modules/type/.a"
    AssertExist  "_testing/destination/node_modules/type/..a"
    AssertExist  "_testing/destination/.vscode/a"
    AssertExist  "_testing/destination/.vscode/.a"
    AssertExist  "_testing/destination/.vscode/..a"
    AssertNotExist  "_testing/destination/.git"
    AssertExist  "_testing/destination/..d/a"
    AssertExist  "_testing/destination/..d/.a"
    AssertExist  "_testing/destination/..d/..a"
    DeleteFolder  "_testing"
}

function  CopyFolder() {
    local  source="$1"
    local  destination="$2"
    local  ignoreDotGit="$3"  #// ${True}, ${False}(default)
    local  excludeOption="--exclude=./.git"
    source="$( CutLastOf  "${source}"  "/" )"
    destination="$( CutLastOf  "${destination}"  "/" )"
    if [ "${ignoreDotGit}" != ""  -a  "${ignoreDotGit}" != "${excludeOption}" ]; then
        TestError  "Bad option: ${ignoreDotGit}"
        return  "${False}"
    fi

    mkdir -p  "${destination}/"
    if [ "${ignoreDotGit}" == "${excludeOption}" ]; then
        ls -a "${source}" | grep -v  -e "^\.git$"  -e "^\.$"  -e "^\.\.$" | xargs  -I {} \
            cp -Rap  "${source}/{}"  "${destination}/"
    else
        ls -a "${source}" | grep -v  -e "^\.$"  -e "^\.\.$" | xargs  -I {} \
            cp -Rap  "${source}/{}"  "${destination}/"
    fi
}

function  DeleteFolder() {
    local  folderPath="$1"
    local  retryCount=5

    while true; do
        rm -rf  "${folderPath}"
        if [ "$?" == "${True}" ]; then
            return
        fi
        retryCount="$(( ${retryCount} - 1 ))"
        if [ "${retryCount}" == "0" ]; then
            Error  "Cannot delete a folder \"${folderPath}\""
        fi
        sleep 2s
    done
}

function  GetBooleanString() {
    if [ "$1" == "${True}" ]; then
        echo  "True"
    elif [ "$1" == "${False}" ]; then
        echo  "False"
    else
        echo  "$1"
    fi
}

function  Test_CutLastOf() {
    echo  ""
    echo  "### Test_CutLastOf"

    local  result="$(CutLastOf "aba" "a")"
    if [ "${result}" != "ab" ]; then
        TestError  "CutLastOf (1)"
    fi

    local  result="$(CutLastOf "aba" "x")"
    if [ "${result}" != "aba" ]; then
        TestError  "CutLastOf (2)"
    fi

    local  result="$(CutLastOf "abc" "bc")"
    if [ "${result}" != "a" ]; then
        TestError  "CutLastOf (3)"
    fi
}

function  CutLastOf() {
    local  wholeString="$1"
    local  lastExpected="$2"

    if [ "${wholeString:${#wholeString}-${#lastExpected}:${#lastExpected}}" == "${lastExpected}" ]; then
        echo  "${wholeString:0:${#wholeString}-${#lastExpected}}"
    else
        echo  "${wholeString}"
    fi
}

function  gitInitOption() {
    if [ "$( LessThanVersion "$(git --version)" "2.31.1")" == "${True}" ]; then
        echo  ""
    else
        echo  "-bmain"  #// "-b main" occurs an error in bash debug
    fi
}

function  GitStatusCurrentFolder() {

    local  gitStatus="$( git status --short )"
    local  gitStatusCurrent=""
    local  oldIFS="$IFS"
    IFS=$'\n'
    lines=( ${gitStatus} )
    IFS="$oldIFS"
    for  gitState  in "${lines[@]}"; do

        if [ "${gitState:3:3}" != "../" ]; then
            echo  "${gitState}"
        fi
    done
}

function  Test_LessThanVersion() {
    echo  ""
    echo  "### Test_LessThanVersion"
    if [ "$( LessThanVersion "0.0.0" "0.0.0" )" != "${False}" ]; then  TestError  ;fi
    if [ "$( LessThanVersion "0.0.0" "0.0.1" )" != "${True}"  ]; then  TestError  ;fi
    if [ "$( LessThanVersion "0.0.0" "0.1.0" )" != "${True}"  ]; then  TestError  ;fi
    if [ "$( LessThanVersion "0.0.0" "1.0.0" )" != "${True}"  ]; then  TestError  ;fi
    if [ "$( LessThanVersion "0.2.0" "0.1.9" )" != "${False}" ]; then  TestError  ;fi
    if [ "$( LessThanVersion "0.1.9" "0.1.9" )" != "${False}" ]; then  TestError  ;fi
    if [ "$( LessThanVersion "0.1.9" "0.2.0" )" != "${True}"  ]; then  TestError  ;fi
    if [ "$( LessThanVersion "2.11.9" "2.9.11" )" != "${False}" ]; then  TestError  ;fi
    if [ "$( LessThanVersion "2.9.11" "2.11.9" )" != "${True}"  ]; then  TestError  ;fi
    if [ "$( LessThanVersion "2.0.0" "1.9.9" )" != "${False}" ]; then  TestError  ;fi
    if [ "$( LessThanVersion "1.9.9" "1.9.9" )" != "${False}" ]; then  TestError  ;fi
    if [ "$( LessThanVersion "1.9.9" "2.0.0" )" != "${True}"  ]; then  TestError  ;fi
}

# LessThanVersion
#     if [ "$( LessThanVersion "$(git --version)" "2.31.1")" == "${True}" ]; then
function  LessThanVersion() {
    local  textContainsVersionA="$1"
    local  textContainsVersionB="$2"
    local  isGoodFormat="${True}"
    echo "${textContainsVersionA}" | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+" > /dev/null  ||  isGoodFormat="${False}"
    echo "${textContainsVersionB}" | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+" > /dev/null  ||  isGoodFormat="${False}"
    if [ "${isGoodFormat}" == "${False}" ]; then
        Error  "\"${textContainsVersionA}\" or \"${textContainsVersionB}\" is not semantic version."
    fi

    local  numbersA=( $( echo "${textContainsVersionA}" | grep -o -e "[0-9]\+" ) )
    local  numbersB=( $( echo "${textContainsVersionB}" | grep -o -e "[0-9]\+" ) )
    if [ "${numbersA[0]}" -lt "${numbersB[0]}" ]; then
        echo "${True}"
        return
    elif [ "${numbersA[0]}" == "${numbersB[0]}" ]; then
        if [ "${numbersA[1]}" -lt "${numbersB[1]}" ]; then
            echo "${True}"
            return
        elif [ "${numbersA[1]}" == "${numbersB[1]}" ]; then
            if [ "${numbersA[2]}" -lt "${numbersB[2]}" ]; then
                echo "${True}"
                return
            fi
        fi
    fi
    echo "${False}"
}

function  Test_Assert() {
    echo  ""
    echo  "### Test_Assert"
    DeleteFolder  "_testing"
    mkdir -p "_testing/build"
    echo "x" > "_testing/build/out"
    echo "x" > "_testing/build/out X"

    AssertExist  "_testing/build/out"
    AssertNotExist  "_testing/build/not_found"
    AssertInstalled  "cat"

    local  out="$(x="$( 
        AssertExist  "_testing/build/not_found"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
    local  out="$(x="$( 
        AssertNotExist  "_testing/build/out"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
    local  out="$(x="$( 
        AssertInstalled  "cats"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi

    local  out="$(x="$( 
        AssertReadOnly  "_testing/build/out"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi

    chmod -w  "_testing/build/out"
    AssertReadOnly  "_testing/build/out"

    local  out="$(x="$( 
        AssertNotReadOnly  "_testing/build/out"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi

    chmod +w  "_testing/build/out"
    AssertNotReadOnly  "_testing/build/out"

    #// contains space
    AssertExist  "_testing/build/out X"
    AssertNotExist  "_testing/build/out not_found"

    local  out="$(x="$( 
        AssertExist  "_testing/build/out not_found"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi
    local  out="$(x="$( 
        AssertNotExist  "_testing/build/out X"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi

    local  out="$(x="$( 
        AssertReadOnly  "_testing/build/out X"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi

    chmod -w  "_testing/build/out X"
    AssertReadOnly  "_testing/build/out X"

    local  out="$(x="$( 
        AssertNotReadOnly  "_testing/build/out X"
    )" && echo "$x" || echo "(assert failed)" )"
    if [ "${out}" != "(assert failed)" ]; then  Error  ;fi

    chmod +w  "_testing/build/out X"
    AssertNotReadOnly  "_testing/build/out X"
}

function  AssertExist() {
    local  path="$1"
    local  leftOfWildcard="${path%\**}"
    if [ "${leftOfWildcard}" == "${path}" ]; then  #// No wildcard

        if [ ! -e "${path}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    else
        local  rightOfWildcard="${path##*\*}"
        if [ ! -e "${leftOfWildcard}"*"${rightOfWildcard}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    fi
}

function  AssertNotExist() {
    local  path="$1"

    if [ -e "${path}" ]; then
        Error  "ERROR: Found \"${path}\""
    fi
}

function  AssertReadOnly() {
    local  path="$1"
    local  writable=${False}

    local  attributes="$(ls -la "${path}")"
    echo "${attributes:0:10}" | grep w  > /dev/null  &&  writable=${True}

    if [ "${writable}" == "${True}" ]; then
        Error  "ERROR: Not read only file \"${path}\""
    fi
}

function  AssertNotReadOnly() {
    local  path="$1"
    local  writable=${False}

    local  attributes="$(ls -la "${path}")"
    echo "${attributes:0:10}" | grep w  > /dev/null  &&  writable=${True}

    if [ "${writable}" == "${False}" ]; then
        Error  "ERROR: Read only file \"${path}\""
    fi
}

function  AssertInstalled() {
    local  checkingCommand="$1"
    local  exists=${False}
    which "${checkingCommand}" > /dev/null  &&  exists=${True}

    if [ "${exists}" == ${False} ]; then
        Error  "ERROR: Not installed \"${checkingCommand}\" command"
    fi
}

function  AssertContents() {
    local  filePath="$1"
    local  expectedContents="$2"

    local  result="$(cat "${filePath}")"
    if [ "${result}" != "$( echo -e "${expectedContents}" )" ]; then
        Error  "ERROR: Not expected contents in ${filePath}: ${result}"
    fi
}

function  Test_ErrorIfLastIs() {
    echo  ""
    echo  "### Test_ErrorIfLastIs"

    local  output="$( Test_Sub1_ErrorIfLastIs )"
    local  answer="$( echo -e 'OK\nstdout\n(ERROR)\n' )"
    if [ "${output}" != "${answer}" ]; then
        Error  "ERROR: in Test_ErrorIfLastIs 1"
    fi

    local  output="$( Test_Sub2_ErrorIfLastIs )"
    local  answer="$( echo -e '(error_symbol) OK\nPass\n' )"
    if [ "${output}" != "${answer}" ]; then
        Error  "ERROR: in Test_ErrorIfLastIs 2"
    fi
}

function  Test_Sub1_ErrorIfLastIs() {
    local  output=""

    output="$( echo "OK" || echo "(ERROR)" )"
    echo  "${output}"
    ErrorIfLastIs  "${output}"  "(ERROR)"

    output="$( TestReturn1 || echo "(ERROR)" )"
    echo  "${output}"
    ErrorIfLastIs  "${output}"  "(ERROR)"

    echo  "not reach here"
}

function  Test_Sub2_ErrorIfLastIs() {
    local  output=""

    output="$( echo "(error_symbol) OK" || echo "(error_symbol)" )"
    echo  "${output}"
    ErrorIfLastIs  "${output}"  "(error_symbol)"

    echo  "Pass"
}

function  TestReturn1()
{
    echo  "stdout"
	return  1
}

# ErrorIfLastIs
#     Error check in $( )
#     variable="$( command  || echo "(ERROR)" )"
#     ErrorIfLastIs  "${output}"  "(ERROR)"
function  ErrorIfLastIs() {
    local  output="$1"
    local  tag="$2"

    local  last="${output:${#output}-${#tag}:${#tag}}"

    if [ "${last}" == "${tag}" ]; then
        exit  2
    fi
}

function  Test_Error() {
    echo  ""
    echo  "### Test_Error"
    local  currentErrorCount="${ErrorCount}"

    #// Test
    TestError  "Test_Error"
    if [ ${ErrorCount} == ${currentErrorCount} ]; then
        echo  "Error: in Error"
        exit  1
    fi
    ErrorCount="${currentErrorCount}"

    #// Test
    currentErrorCount="${ErrorCount}"
    StartErrorTest
    EndErrorTest  "Test of no error error"
    if [ ${ErrorCount} == ${currentErrorCount} ]; then
        echo  "Error: test 1 in StartErrorTest or EndErrorTest"
        exit  1
    fi
    ErrorCount="${currentErrorCount}"

    #// Test
    currentErrorCount="${ErrorCount}"
    StartErrorTest
    TestError  "Test of StartErrorTest (2)"
    EndErrorTest  "Test of StartErrorTest (2)"
    if [ ${ErrorCount} != ${currentErrorCount} ]; then
        echo  "Error: test 2 in StartErrorTest or EndErrorTest"
        exit  1
    fi
    ErrorCount="${currentErrorCount}"

    echo  "Passed Test_Error."
}

function  StartErrorTest() {
    ErrorCountBeforeStart=${ErrorCount}
}
NotInErrorTest=-1
ErrorCountBeforeStart=${NotInErrorTest}

function  EndErrorTest() {
    local  expectedErrorMessage="$1"
    local  errorCountBeforeStart="${ErrorCountBeforeStart}"
    ErrorCountBeforeStart="${NotInErrorTest}"

    if [ "${ErrorCount}" == "${errorCountBeforeStart}" ]; then
        if [ "${expectedErrorMessage}" == "" ]; then
            TestError  "ERROR: EndErrorTest has no parameter"
        else
            TestError  "ERROR: Expected an error of \"${expectedErrorMessage}\" but no error"
        fi
    elif [ "${expectedErrorMessage}" != "${LastErrorMessage}" ]; then
        if [ "${expectedErrorMessage}" == "" ]; then
            TestError  "ERROR: EndErrorTest has no parameter. \"${LastErrorMessage}\" error was occurred"
        else
            TestError  "ERROR: Expected an error of \"${expectedErrorMessage}\" but \"${LastErrorMessage}\""
        fi
    else
        ErrorCount="${errorCountBeforeStart}"
    fi
}

# ExitIfMatched
#     Check exit code and return code in $( ). If checking was failed, do "exit" command.
# Example:
#     local  out="$(x="$( command )" && echo "$x" || echo "(ERROR:$?)" )"
#     ExitIfMatched  "${out}"  '^\(ERROR:([0-9]*)\)$'
function  ExitIfMatched() {
    local  output="$1"
    local  regularExpression="$2"

    if [[ "${output}" =~ ${regularExpression} ]]; then
        local  exitCode="$( echo "${output}"  |  sed -E  's/'"${regularExpression}"'/\1/')"
        exit  "${exitCode}"
    fi
}

function  TestError() {
    local  errorMessage="$1"
    if [ "${errorMessage}" == "" ]; then
        errorMessage="a test error"
    fi
    if [ "${ErrorCountBeforeStart}" == "${NotInErrorTest}" ]; then

        echo  "ERROR: ${errorMessage}"
    fi
    LastErrorMessage="${errorMessage}"
    ErrorCount=$(( ${ErrorCount} + 1 ))
}
ErrorCount=0
LastErrorMessage=""

function  Error() {
    local  errorMessage="$1"
    local  exitCode="$2"
    if [ "${errorMessage}" == "" ]; then
        errorMessage="ERROR"
    fi
    if [ "${exitCode}" == "" ]; then  exitCode=2  ;fi

    echo  "${errorMessage}" >&2
    exit  "${exitCode}"
}

function  EndOfTest() {
    echo  ""
    echo  "ErrorCount: ${ErrorCount}"
    if [ "${ErrorCount}" == "0" ]; then
        echo  "Pass."
        local  message="Environment ${TestEnvironmentNum}:"
        message="${message} IsGitWorking = $( GetBooleanString ${IsGitWorking} ),"
        message="${message} InGitWorking = $( GetBooleanString ${InGitWorking} )."
        echo  "${message}"
        echo  "Also, you must test other environments. All environment numbers are 1,2,3."
    fi
}

function  DetectTestEnvironment() {
    local  gitWorkingRootPath="$( GetGitWorkingRootPath )"
    if [ "${gitWorkingRootPath}" == "" ]; then
        TestEnvironmentNum=1
        IsGitWorking="${False}"
        InGitWorking="${False}"
    elif [ "${gitWorkingRootPath}/test" == "${PWD}" ]; then
        TestEnvironmentNum=2
        IsGitWorking="${True}"
        InGitWorking="${False}"
    else
        TestEnvironmentNum=3
        IsGitWorking="${False}"
        InGitWorking="${True}"
    fi
}

#// pp "$config"
#// pp "$config" config
#// pp "$array" array  ${#array[@]}  "${array[@]}"
#// pp "123"
#// $( pp "$config" >&2 )
function  pp() {
    local  value="$1"
    local  variableName="$2"
    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi  #// Add spaces
    local  oldIFS="$IFS"
    IFS=$'\n'
    local  valueLines=( ${value} )
    IFS="$oldIFS"

    local  type=""
    if [ "${variableName}" != "" ]; then
        if [[ "$(declare -p ${variableName} 2>&1 )" =~ "declare -a" ]]; then
            local  type="array"
        fi
    fi
    if [ "${type}" == "" ]; then
        if [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
            local  type="oneLine"
        else
            local  type="multiLine"
        fi
    fi

    if [[ "${type}" == "oneLine" ]]; then
        echo  "@@@${variableName}= \"${value}\" ---------------------------"  >&2
    elif [[ "${type}" == "multiLine" ]]; then
        echo  "@@@${variableName}---------------------------"  >&2
        echo  "\"${value}\"" >&2
    elif [[ "${type}" == "array" ]]; then
        echo  "@@@${variableName}---------------------------"  >&2
        local  count="$3"
        if [ "${count}" == "" ]; then
            echo  "[0]: \"$4\""  >&2
            echo  "[1]: ERROR: pp parameter is too few"  >&2
        else
            local  i="0"
            for (( i = 0; i < ${count}; i += 1 ));do
                echo  "[$i]: \"$4\""  >&2
                shift
            done
        fi
    else
        echo  "@@@${variableName}? ---------------------------"  >&2
    fi
}

True=0
False=1
GitInitOption=$(gitInitOption) 
TestEnvironmentNum=0
InGitWorking=""
IsGitWorking=""
LocommitEMail="locommit@example.com"
LocommitUser="locommit"

AllTest
